version: "3.8"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: 100m
    max-file: 100

networks:
  docker-network:
    driver: bridge

services:

  # DATABASE
  postgres_db:
    container_name: neox-db
    image: bitnami/postgresql:latest
    platform: linux/amd64
    ports:
      - ${DB_PORT_DOCKER}:${DB_PORT}
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${DB_DATABASE}
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
    networks:
      - docker-network
    logging: *default-logging

  # BACKEND APP
  backend-app:
    container_name: neox-backend
    # depends_on:
    # - postgres_db
    build: neox-api
    restart: unless-stopped
    ports:
      - ${BACKEND_PORT_DOCKER}:${BACKEND_PORT}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT_DOCKER}
      - JWT_SECRET=${JWT_SECRET}
    stdin_open: true
    tty: true
    volumes:
      - ./neox-api:/app
      - /app/node_modules
    networks:
      - default

volumes:
  db-data:
