version: "3.8"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: 100m
    max-file: 100

networks:
  neox-network:
    driver: bridge

services:

  # DATABASE
  neox_prod_db:
    container_name: prod-neox-db
    image: bitnami/postgresql:latest
    platform: linux/amd64
    ports:
      - ${DB_PORT}:5432
    restart: always
    volumes:
      - neox-prod-db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${DB_DATABASE}
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
    networks:
      - neox-network
    logging: *default-logging

volumes:
  neox-prod-db-data:
