version: "3.8"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: 100m
    max-file: 100

networks:
  neox-dev-network:
    driver: bridge

services:

  # DATABASE
  dev-db:
    container_name: dev-db
    image: bitnami/postgresql:latest
    platform: linux/amd64
    ports:
      - ${DB_PORT}:5432
    restart: always
    volumes:
      - neox-dev-db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${DB_DATABASE}
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
    networks:
      - neox-dev-network
    logging: *default-logging


  # API
  dev-api:
    container_name: dev-api
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    environment:
      - DB_HOST=dev-db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - START_SCRIPT=${START_SCRIPT}
      - RUN_TESTS=${RUN_TESTS}
    depends_on:
      - dev-db
    networks:
      - neox-dev-network

volumes:
  neox-dev-db-data:
