version: "3.8"

services:
  # FRONTEND
  production-frontend:
    build:
      context: .
      args:
        APP_NAME: ${APP_NAME}
      dockerfile: Dockerfile.production
    image: neox-prod-fe:latest
    container_name: neox-prod-fe
    ports:
      - "80:${APP_PORT}"
    restart: unless-stopped
